// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/dynamodb/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CardsAttributes  holds the attributes for the "cards " table.
	CardsAttributes = []*schema.Attribute{
		{Name: "id", Type: field.TypeInt},
		{Name: "number", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "in_hook", Type: field.TypeString},
	}
	// CardsTable holds the schema information for the "cards" table.
	CardsTable = &schema.Table{
		Name:       "cards",
		Attributes: CardsAttributes,
		PrimaryKey: []*schema.KeySchema{
			{AttributeName: "id", KeyType: schema.KeyType("HASH")},
		},
	}
	// UsersAttributes  holds the attributes for the "users " table.
	UsersAttributes = []*schema.Attribute{
		{Name: "id", Type: field.TypeInt},
		{Name: "version", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "worth", Type: field.TypeUint},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Attributes: UsersAttributes,
		PrimaryKey: []*schema.KeySchema{
			{AttributeName: "id", KeyType: schema.KeyType("HASH")},
		},
	}
	// UserFriendsAttributes  holds the attributes for the "user_friends " table.
	UserFriendsAttributes = []*schema.Attribute{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "friend_id", Type: field.TypeInt},
	}
	// UserFriendsTable holds the schema information for the "user_friends" table.
	UserFriendsTable = &schema.Table{
		Name:       "user_friends",
		Attributes: UserFriendsAttributes,
		PrimaryKey: []*schema.KeySchema{
			{AttributeName: "user_id", KeyType: schema.KeyType("HASH")},
			{AttributeName: "friend_id", KeyType: schema.KeyType("RANGE")},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CardsTable,
		UsersTable,
		UserFriendsTable,
	}
)
