// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"entgo.io/ent/dialect/dynamodb"
	"entgo.io/ent/dialect/dynamodb/dynamodbgraph"
	"entgo.io/ent/entc/integration/dynamodb/json/ent/predicate"
	"entgo.io/ent/entc/integration/dynamodb/json/ent/schema"
	"entgo.io/ent/entc/integration/dynamodb/json/ent/user"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetT sets the "t" field.
func (uu *UserUpdate) SetT(s *schema.T) *UserUpdate {
	uu.mutation.SetT(s)
	return uu
}

// ClearT clears the value of the "t" field.
func (uu *UserUpdate) ClearT() *UserUpdate {
	uu.mutation.ClearT()
	return uu
}

// SetURL sets the "url" field.
func (uu *UserUpdate) SetURL(u *url.URL) *UserUpdate {
	uu.mutation.SetURL(u)
	return uu
}

// ClearURL clears the value of the "url" field.
func (uu *UserUpdate) ClearURL() *UserUpdate {
	uu.mutation.ClearURL()
	return uu
}

// SetRaw sets the "raw" field.
func (uu *UserUpdate) SetRaw(jm json.RawMessage) *UserUpdate {
	uu.mutation.SetRaw(jm)
	return uu
}

// AppendRaw appends jm to the "raw" field.
func (uu *UserUpdate) AppendRaw(jm json.RawMessage) *UserUpdate {
	uu.mutation.AppendRaw(jm)
	return uu
}

// ClearRaw clears the value of the "raw" field.
func (uu *UserUpdate) ClearRaw() *UserUpdate {
	uu.mutation.ClearRaw()
	return uu
}

// SetDirs sets the "dirs" field.
func (uu *UserUpdate) SetDirs(h []http.Dir) *UserUpdate {
	uu.mutation.SetDirs(h)
	return uu
}

// AppendDirs appends h to the "dirs" field.
func (uu *UserUpdate) AppendDirs(h []http.Dir) *UserUpdate {
	uu.mutation.AppendDirs(h)
	return uu
}

// ClearDirs clears the value of the "dirs" field.
func (uu *UserUpdate) ClearDirs() *UserUpdate {
	uu.mutation.ClearDirs()
	return uu
}

// SetInts sets the "ints" field.
func (uu *UserUpdate) SetInts(i []int) *UserUpdate {
	uu.mutation.SetInts(i)
	return uu
}

// AppendInts appends i to the "ints" field.
func (uu *UserUpdate) AppendInts(i []int) *UserUpdate {
	uu.mutation.AppendInts(i)
	return uu
}

// ClearInts clears the value of the "ints" field.
func (uu *UserUpdate) ClearInts() *UserUpdate {
	uu.mutation.ClearInts()
	return uu
}

// SetFloats sets the "floats" field.
func (uu *UserUpdate) SetFloats(f []float64) *UserUpdate {
	uu.mutation.SetFloats(f)
	return uu
}

// AppendFloats appends f to the "floats" field.
func (uu *UserUpdate) AppendFloats(f []float64) *UserUpdate {
	uu.mutation.AppendFloats(f)
	return uu
}

// ClearFloats clears the value of the "floats" field.
func (uu *UserUpdate) ClearFloats() *UserUpdate {
	uu.mutation.ClearFloats()
	return uu
}

// SetStrings sets the "strings" field.
func (uu *UserUpdate) SetStrings(s []string) *UserUpdate {
	uu.mutation.SetStrings(s)
	return uu
}

// AppendStrings appends s to the "strings" field.
func (uu *UserUpdate) AppendStrings(s []string) *UserUpdate {
	uu.mutation.AppendStrings(s)
	return uu
}

// ClearStrings clears the value of the "strings" field.
func (uu *UserUpdate) ClearStrings() *UserUpdate {
	uu.mutation.ClearStrings()
	return uu
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uu.hooks) == 0 {
		affected, err = uu.dynamodbSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uu.mutation = mutation
			affected, err = uu.dynamodbSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uu.hooks) - 1; i >= 0; i-- {
			if uu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) dynamodbSave(ctx context.Context) (n int, err error) {
	_spec := &dynamodbgraph.UpdateSpec{
		Node: &dynamodbgraph.NodeSpec{
			Table: user.Table,
			Keys:  user.Keys,
			ID: &dynamodbgraph.FieldSpec{
				Type: field.TypeInt,
				Key:  user.FieldID,
			},
		},
	}
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *dynamodb.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.T(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldT,
		})
	}
	if uu.mutation.TCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldT,
		})
	}
	if value, ok := uu.mutation.URL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldURL,
		})
	}
	if uu.mutation.URLCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldURL,
		})
	}
	if value, ok := uu.mutation.Raw(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldRaw,
		})
	}
	if uu.mutation.RawCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldRaw,
		})
	}
	if value, ok := uu.mutation.Dirs(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldDirs,
		})
	}
	if uu.mutation.DirsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldDirs,
		})
	}
	if value, ok := uu.mutation.Ints(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldInts,
		})
	}
	if uu.mutation.IntsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldInts,
		})
	}
	if value, ok := uu.mutation.Floats(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldFloats,
		})
	}
	if uu.mutation.FloatsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldFloats,
		})
	}
	if value, ok := uu.mutation.Strings(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldStrings,
		})
	}
	if uu.mutation.StringsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldStrings,
		})
	}
	if n, err = dynamodbgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		return 0, err
	}
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetT sets the "t" field.
func (uuo *UserUpdateOne) SetT(s *schema.T) *UserUpdateOne {
	uuo.mutation.SetT(s)
	return uuo
}

// ClearT clears the value of the "t" field.
func (uuo *UserUpdateOne) ClearT() *UserUpdateOne {
	uuo.mutation.ClearT()
	return uuo
}

// SetURL sets the "url" field.
func (uuo *UserUpdateOne) SetURL(u *url.URL) *UserUpdateOne {
	uuo.mutation.SetURL(u)
	return uuo
}

// ClearURL clears the value of the "url" field.
func (uuo *UserUpdateOne) ClearURL() *UserUpdateOne {
	uuo.mutation.ClearURL()
	return uuo
}

// SetRaw sets the "raw" field.
func (uuo *UserUpdateOne) SetRaw(jm json.RawMessage) *UserUpdateOne {
	uuo.mutation.SetRaw(jm)
	return uuo
}

// AppendRaw appends jm to the "raw" field.
func (uuo *UserUpdateOne) AppendRaw(jm json.RawMessage) *UserUpdateOne {
	uuo.mutation.AppendRaw(jm)
	return uuo
}

// ClearRaw clears the value of the "raw" field.
func (uuo *UserUpdateOne) ClearRaw() *UserUpdateOne {
	uuo.mutation.ClearRaw()
	return uuo
}

// SetDirs sets the "dirs" field.
func (uuo *UserUpdateOne) SetDirs(h []http.Dir) *UserUpdateOne {
	uuo.mutation.SetDirs(h)
	return uuo
}

// AppendDirs appends h to the "dirs" field.
func (uuo *UserUpdateOne) AppendDirs(h []http.Dir) *UserUpdateOne {
	uuo.mutation.AppendDirs(h)
	return uuo
}

// ClearDirs clears the value of the "dirs" field.
func (uuo *UserUpdateOne) ClearDirs() *UserUpdateOne {
	uuo.mutation.ClearDirs()
	return uuo
}

// SetInts sets the "ints" field.
func (uuo *UserUpdateOne) SetInts(i []int) *UserUpdateOne {
	uuo.mutation.SetInts(i)
	return uuo
}

// AppendInts appends i to the "ints" field.
func (uuo *UserUpdateOne) AppendInts(i []int) *UserUpdateOne {
	uuo.mutation.AppendInts(i)
	return uuo
}

// ClearInts clears the value of the "ints" field.
func (uuo *UserUpdateOne) ClearInts() *UserUpdateOne {
	uuo.mutation.ClearInts()
	return uuo
}

// SetFloats sets the "floats" field.
func (uuo *UserUpdateOne) SetFloats(f []float64) *UserUpdateOne {
	uuo.mutation.SetFloats(f)
	return uuo
}

// AppendFloats appends f to the "floats" field.
func (uuo *UserUpdateOne) AppendFloats(f []float64) *UserUpdateOne {
	uuo.mutation.AppendFloats(f)
	return uuo
}

// ClearFloats clears the value of the "floats" field.
func (uuo *UserUpdateOne) ClearFloats() *UserUpdateOne {
	uuo.mutation.ClearFloats()
	return uuo
}

// SetStrings sets the "strings" field.
func (uuo *UserUpdateOne) SetStrings(s []string) *UserUpdateOne {
	uuo.mutation.SetStrings(s)
	return uuo
}

// AppendStrings appends s to the "strings" field.
func (uuo *UserUpdateOne) AppendStrings(s []string) *UserUpdateOne {
	uuo.mutation.AppendStrings(s)
	return uuo
}

// ClearStrings clears the value of the "strings" field.
func (uuo *UserUpdateOne) ClearStrings() *UserUpdateOne {
	uuo.mutation.ClearStrings()
	return uuo
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	var (
		err  error
		node *User
	)
	if len(uuo.hooks) == 0 {
		node, err = uuo.dynamodbSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uuo.mutation = mutation
			node, err = uuo.dynamodbSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uuo.hooks) - 1; i >= 0; i-- {
			if uuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, uuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*User)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from UserMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) dynamodbSave(ctx context.Context) (_node *User, err error) {
	_spec := &dynamodbgraph.UpdateSpec{
		Node: &dynamodbgraph.NodeSpec{
			Table: user.Table,
			Keys:  user.Keys,
			ID: &dynamodbgraph.FieldSpec{
				Type: field.TypeInt,
				Key:  user.FieldID,
			},
		},
	}
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing User.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Keys = make([]string, 0, len(fields))
		_spec.Node.Keys = append(_spec.Node.Keys, user.FieldID)
		for _, f := range fields {
			if !user.ValidKey(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Keys = append(_spec.Node.Keys, f)
			}
		}
	}
	if value, ok := uuo.mutation.T(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldT,
		})
	}
	if uuo.mutation.TCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldT,
		})
	}
	if value, ok := uuo.mutation.URL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldURL,
		})
	}
	if uuo.mutation.URLCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldURL,
		})
	}
	if value, ok := uuo.mutation.Raw(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldRaw,
		})
	}
	if uuo.mutation.RawCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldRaw,
		})
	}
	if value, ok := uuo.mutation.Dirs(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldDirs,
		})
	}
	if uuo.mutation.DirsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldDirs,
		})
	}
	if value, ok := uuo.mutation.Ints(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldInts,
		})
	}
	if uuo.mutation.IntsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldInts,
		})
	}
	if value, ok := uuo.mutation.Floats(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldFloats,
		})
	}
	if uuo.mutation.FloatsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldFloats,
		})
	}
	if value, ok := uuo.mutation.Strings(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &dynamodbgraph.FieldSpec{
			Type:  field.TypeJSON,
			Value: value,
			Key:   user.FieldStrings,
		})
	}
	if uuo.mutation.StringsCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &dynamodbgraph.FieldSpec{
			Type: field.TypeJSON,
			Key:  user.FieldStrings,
		})
	}
	_spec.Item = _node.item
	_spec.Assign = func(item interface{}) error {
		_node = &User{}
		if err := _node.FromItem(item); err != nil {
			return err
		}
		_node.config = uuo.config

		return nil
	}
	if err = dynamodbgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		return nil, err
	}
	return _node, nil
}
