// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// EdgePets holds the string denoting the pets edge name in mutations.
	EdgePets = "pets"
	// Table holds the table name of the user in the database.
	Table = "users"
	// GroupsTable is the table that holds the groups relation/edge. The primary key declared below.
	GroupsTable = "group_users"
	// GroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupsInverseTable = "groups"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "users"
	// ParentAttribute is the table column denoting the parent relation/edge.
	ParentAttribute = "user_children"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "users"
	// ChildrenAttribute is the table column denoting the children relation/edge.
	ChildrenAttribute = "user_children"
	// PetsTable is the table that holds the pets relation/edge.
	PetsTable = "pets"
	// PetsInverseTable is the table name for the Pet entity.
	// It exists in this package in order to avoid circular dependency with the "pet" package.
	PetsInverseTable = "pets"
	// PetsAttribute is the table column denoting the pets relation/edge.
	PetsAttribute = "user_pets"
)

// Keys holds all DynamoDB keys for user fields.
var Keys = []string{
	FieldID,
	"user_children",
	"group_id",
}

// ForeignKeys holds the Mongo foreign-keys that are owned by the User type.
var ForeignKeys = []string{
	"user_children",
}

var (
	// GroupsAttribute and GroupsAttribute2 are the collection keys denoting the
	// primary key for the groups relation (M2M).
	GroupsAttributes = []string{"group_id", "user_id"}
)

// ValidKey reports if the key is valid (one of keys of collection's fields).
func ValidKey(key string) bool {
	for i := range Keys {
		if key == Keys[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if key == ForeignKeys[i] {
			return true
		}
	}
	return false
}
