// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/dynamodb/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersAttributes  holds the attributes for the "users " table.
	UsersAttributes = []*schema.Attribute{
		{Name: "id", Type: field.TypeInt},
		{Name: "t", Type: field.TypeJSON},
		{Name: "url", Type: field.TypeJSON},
		{Name: "raw", Type: field.TypeJSON},
		{Name: "dirs", Type: field.TypeJSON},
		{Name: "ints", Type: field.TypeJSON},
		{Name: "floats", Type: field.TypeJSON},
		{Name: "strings", Type: field.TypeJSON},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Attributes: UsersAttributes,
		PrimaryKey: []*schema.KeySchema{
			{AttributeName: "id", KeyType: schema.KeyType("HASH")},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)
